version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-course-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - redis
      - qdrant
    networks:
      - ai-course-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ai-course-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - ai-course-network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai-course-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
    networks:
      - ai-course-network
    restart: unless-stopped

  bull-board:
    image: deadly0/bull-board
    container_name: ai-course-bull-board
    ports:
      - "3010:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    depends_on:
      - redis
    networks:
      - ai-course-network
    restart: unless-stopped

volumes:
  redis-data:
  qdrant-data:

networks:
  ai-course-network:
    driver: bridge